name: file1 changes

on: 
  pull_request:
    branches:
     - main
    paths:
      - 'file1'
  merge_group:
    types: [checks_requested]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print anything
        run : |
          sleep 2m
          echo "hello world"
